spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    # session回话存储类型
    store-type: redis
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    ## 热加载 静态资源不重启
    restart:
      exclude: templates/**,static/**
  redis:
    database: 0
    host: localhost
    pool:
      min-idle: 1
    timeout: 3000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: xunwu_topic
  mail:
    host: smtp.163.com
    username: @163.com
    password: 
    properties:
      mail:
        smtp:
          auth: true



security:
  basic:
    enabled: false

logging:
  level: debug

server:
  error:
    whitelabel:
      enabled: false


qiniu:
  AccessKey: -
  SecretKey: 
  Bucket: xunwu-image-repository
  cdn:
    prefix: http://7xo6gy.com1.z0.glb.clouddn.com/
#    prefix: http://p2y1v9py1.bkt.clouddn.com/

es:
  clusterName: xunwu-es
  address:
    - ip: 127.0.0.1
      port: 9300

baidu:
  map:
    serverKey: 
#    serverKey: f40jbqRPtIH5igipC5y3dZwaQvTSBaWE
    geoConvApi: http://api.map.baidu.com/geocoder/v2/?
  lbs:
    create: http://api.map.baidu.com/geodata/v3/poi/create
    query: http://api.map.baidu.com/geodata/v3/poi/list?
    update: http://api.map.baidu.com/geodata/v3/poi/update
    delete: http://api.map.baidu.com/geodata/v3/poi/delete
    tableId: 175730
#    tableId: 184277

# 阿里云短信配置 注意替换自己申请的配置
aliyun:
  sms:
    accessKey: 
    accessKeySecret: 
    template:
      code: 








